---
title: "Trabalho de Conclusão de Cusros - FGV T4 Big Data e Analytics"
author: "Ricardo Squassina Lee, Rafael Furlan, Djalma Gomes"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


---
```{r Inicia Ambiente, message=FALSE, include=FALSE}
#Iniciando o ambiente
rm(list = ls())
cat("\014") 
# setwd("~/Tresors/zz-pessoal/FGV/git/TCC")
setwd("./")
```

---
```{r Carrega bibliotecas necessarias, message=FALSE, warning=TRUE, include=FALSE}
if(!require(data.table)) {
  install.packages("data.table")
  library(data.table)
}

if(!require(network)) {
  install.packages("network")
  library(network)
}

if(!require(sna)) {
  install.packages("sna")
  library(sna)
}

if(!require(rgl)) {
  install.packages("rgl")
  library(rgl)
}

```

```{r}
CONSULTAS_CONS <- fread("consultas_cons_cap7.csv", drop = c("V1"))
```

# MapReduce

```{r MapReduce}
CAP_Precip_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$Precip, digits = 0)))
names(CAP_Precip_freq) <- c("CAP","Clima","Freq")

CAP_TMax_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$TMax, digits = 0)))
names(CAP_TMax_freq) <- c("CAP","Clima","Freq")

CAP_Tmin_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$TMin, digits = 0)))
names(CAP_Tmin_freq) <- c("CAP","Clima","Freq")

CAP_Ins_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$Ins, digits = 0)))
names(CAP_Ins_freq) <- c("CAP","Clima","Freq")

CAP_EvapPiche_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$EvapPiche, digits = 0)))
names(CAP_EvapPiche_freq) <- c("CAP","Clima","Freq")

CAP_TempCompMed_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$TempCompMedia, digits = 0)))
names(CAP_TempCompMed_freq) <- c("CAP","Clima","Freq")

CAP_UmidRelMed_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$UmidRelMed, digits = 0)))
names(CAP_UmidRelMed_freq) <- c("CAP","Clima","Freq")

CAP_VelVentMed_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round(CONSULTAS_CONS$VelVentMed, digits = 0)))
names(CAP_VelVentMed_freq) <- c("CAP","Clima","Freq")

CAP_TDelta_freq <- as.data.frame(table(CONSULTAS_CONS$CAP,round((CONSULTAS_CONS$TMax - CONSULTAS_CONS$TMin), digits = 0)))
names(CAP_TDelta_freq) <- c("CAP","Clima","Freq")


```


```{r}
CAP_EvapPiche_freq$FreqRel <- CAP_EvapPiche_freq$Freq/nrow(CONSULTAS_CONS)
CAP_Ins_freq$FreqRel <- CAP_Ins_freq$Freq/nrow(CONSULTAS_CONS)
CAP_Precip_freq$FreqRel <- CAP_Precip_freq$Freq/nrow(CONSULTAS_CONS)
CAP_TDelta_freq$FreqRel <- CAP_TDelta_freq$Freq/nrow(CONSULTAS_CONS)
CAP_TempCompMed_freq$FreqRel <- CAP_TempCompMed_freq$Freq/nrow(CONSULTAS_CONS)
CAP_TMax_freq$FreqRel <- CAP_TMax_freq$Freq/nrow(CONSULTAS_CONS)
CAP_Tmin_freq$FreqRel <- CAP_Tmin_freq$Freq/nrow(CONSULTAS_CONS)
CAP_UmidRelMed_freq$FreqRel <- CAP_UmidRelMed_freq$Freq/nrow(CONSULTAS_CONS)
CAP_VelVentMed_freq$FreqRel <- CAP_VelVentMed_freq$Freq/nrow(CONSULTAS_CONS)

```



```{r}

nrow <- max(unique(as.integer(CAP_EvapPiche_freq$CAP)))
ncol <- max(unique(as.integer(CAP_EvapPiche_freq$Clima)))

MATRIX_EVAPPICHE <- matrix(CAP_EvapPiche_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_EVAPPICHE) <- unique(CAP_EvapPiche_freq$CAP)
colnames(MATRIX_EVAPPICHE) <- unique(CAP_EvapPiche_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_Ins_freq$CAP)))
ncol <- max(unique(as.integer(CAP_Ins_freq$Clima)))

MATRIX_INS <- matrix(CAP_Ins_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_INS) <- unique(CAP_Ins_freq$CAP)
colnames(MATRIX_INS) <- unique(CAP_Ins_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_Precip_freq$CAP)))
ncol <- max(unique(as.integer(CAP_Precip_freq$Clima)))

MATRIX_PRECIP <- matrix(CAP_Precip_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_PRECIP) <- unique(CAP_Precip_freq$CAP)
colnames(MATRIX_PRECIP) <- unique(CAP_Precip_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_TDelta_freq$CAP)))
ncol <- max(unique(as.integer(CAP_TDelta_freq$Clima)))

MATRIX_TDELTA <- matrix(CAP_TDelta_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_TDELTA) <- unique(CAP_TDelta_freq$CAP)
colnames(MATRIX_TDELTA) <- unique(CAP_TDelta_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_TempCompMed_freq$CAP)))
ncol <- max(unique(as.integer(CAP_TempCompMed_freq$Clima)))

MATRIX_TEMPCOMPMED <- matrix(CAP_TempCompMed_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_TEMPCOMPMED) <- unique(CAP_TempCompMed_freq$CAP)
colnames(MATRIX_TEMPCOMPMED) <- unique(CAP_TempCompMed_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_TMax_freq$CAP)))
ncol <- max(unique(as.integer(CAP_TMax_freq$Clima)))

MATRIX_TMAX <- matrix(CAP_TMax_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMAX) <- unique(CAP_TMax_freq$CAP)
colnames(MATRIX_TMAX) <- unique(CAP_TMax_freq$Clima)


```

```{r}

nrow <- max(unique(as.integer(CAP_Tmin_freq$CAP)))
ncol <- max(unique(as.integer(CAP_Tmin_freq$Clima)))

MATRIX_TMIN <- matrix(CAP_Tmin_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMIN) <- unique(CAP_Tmin_freq$CAP)
colnames(MATRIX_TMIN) <- unique(CAP_Tmin_freq$Clima)


```

```{r}

nrow <- max(unique(as.integer(CAP_UmidRelMed_freq$CAP)))
ncol <- max(unique(as.integer(CAP_UmidRelMed_freq$Clima)))

MATRIX_UMIDRELMED <- matrix(CAP_UmidRelMed_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_UMIDRELMED) <- unique(CAP_UmidRelMed_freq$CAP)
colnames(MATRIX_UMIDRELMED) <- unique(CAP_UmidRelMed_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_VelVentMed_freq$CAP)))
ncol <- max(unique(as.integer(CAP_VelVentMed_freq$Clima)))

MATRIX_VELVENTMED <- matrix(CAP_VelVentMed_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_VELVENTMED) <- unique(CAP_VelVentMed_freq$CAP)
colnames(MATRIX_VELVENTMED) <- unique(CAP_VelVentMed_freq$Clima)

```



```{r}

nrow <- max(unique(as.integer(CAP_EvapPiche_freq$CAP)))
ncol <- max(unique(as.integer(CAP_EvapPiche_freq$Clima)))

MATRIX_EVAPPICHE_REL <- matrix(CAP_EvapPiche_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_EVAPPICHE_REL) <- unique(CAP_EvapPiche_freq$CAP)
colnames(MATRIX_EVAPPICHE_REL) <- unique(CAP_EvapPiche_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_Ins_freq$CAP)))
ncol <- max(unique(as.integer(CAP_Ins_freq$Clima)))

MATRIX_INS_REL <- matrix(CAP_Ins_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_INS_REL) <- unique(CAP_Ins_freq$CAP)
colnames(MATRIX_INS_REL) <- unique(CAP_Ins_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_Precip_freq$CAP)))
ncol <- max(unique(as.integer(CAP_Precip_freq$Clima)))

MATRIX_PRECIP_REL <- matrix(CAP_Precip_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_PRECIP_REL) <- unique(CAP_Precip_freq$CAP)
colnames(MATRIX_PRECIP_REL) <- unique(CAP_Precip_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_TDelta_freq$CAP)))
ncol <- max(unique(as.integer(CAP_TDelta_freq$Clima)))

MATRIX_TDELTA_REL <- matrix(CAP_TDelta_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_TDELTA_REL) <- unique(CAP_TDelta_freq$CAP)
colnames(MATRIX_TDELTA_REL) <- unique(CAP_TDelta_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_TempCompMed_freq$CAP)))
ncol <- max(unique(as.integer(CAP_TempCompMed_freq$Clima)))

MATRIX_TEMPCOMPMED_REL <- matrix(CAP_TempCompMed_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_TEMPCOMPMED_REL) <- unique(CAP_TempCompMed_freq$CAP)
colnames(MATRIX_TEMPCOMPMED_REL) <- unique(CAP_TempCompMed_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_TMax_freq$CAP)))
ncol <- max(unique(as.integer(CAP_TMax_freq$Clima)))

MATRIX_TMAX_REL <- matrix(CAP_TMax_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMAX_REL) <- unique(CAP_TMax_freq$CAP)
colnames(MATRIX_TMAX_REL) <- unique(CAP_TMax_freq$Clima)


```

```{r}

nrow <- max(unique(as.integer(CAP_Tmin_freq$CAP)))
ncol <- max(unique(as.integer(CAP_Tmin_freq$Clima)))

MATRIX_TMIN_REL <- matrix(CAP_Tmin_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMIN_REL) <- unique(CAP_Tmin_freq$CAP)
colnames(MATRIX_TMIN_REL) <- unique(CAP_Tmin_freq$Clima)


```

```{r}

nrow <- max(unique(as.integer(CAP_UmidRelMed_freq$CAP)))
ncol <- max(unique(as.integer(CAP_UmidRelMed_freq$Clima)))

MATRIX_UMIDRELMED_REL <- matrix(CAP_UmidRelMed_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_UMIDRELMED_REL) <- unique(CAP_UmidRelMed_freq$CAP)
colnames(MATRIX_UMIDRELMED_REL) <- unique(CAP_UmidRelMed_freq$Clima)

```

```{r}

nrow <- max(unique(as.integer(CAP_VelVentMed_freq$CAP)))
ncol <- max(unique(as.integer(CAP_VelVentMed_freq$Clima)))

MATRIX_VELVENTMED_REL <- matrix(CAP_VelVentMed_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_VELVENTMED_REL) <- unique(CAP_VelVentMed_freq$CAP)
colnames(MATRIX_VELVENTMED_REL) <- unique(CAP_VelVentMed_freq$Clima)

```


## Análise dos grafos:

```{r}
analise <- ls(pattern = "CAP.*")

lapply(analise, function(x) {
  df <- get(x)
  nrow <- length(unique(df$CAP))
  ncol <- length(unique(df$Clima))
  
  matriz <- matrix(df$Freq, nrow = nrow, ncol = ncol)
  
  rownames(matriz) <- unique(df$CID)
  colnames(matriz) <- unique(df$Clima)
  
  degree(matriz, gmode = "twomode", cmode = "indegree")
  closeness(matriz, gmode = "twomode")
  betweenness(matriz, gmode = "twomode")
  
  gplot(
    matriz,
    gmode = "twomode",
    displaylabels = TRUE,
    edge.col = "gray",
    label.cex = 0.7,
    usearrows = FALSE,
    vertex.cex = closeness(matriz, gmode = "twomode") * 3
  )
  title(main = x)
})

```