---
title: "Trabalho de Conclusão de Cusros - FGV T4 Big Data e Analytics"
author: "Ricardo Squassina Lee, Rafael Furlan, Djalma Gomes"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


---
```{r Inicia Ambiente, message=FALSE, include=FALSE}
#Iniciando o ambiente
rm(list = ls())
cat("\014") 
# setwd("~/Tresors/zz-pessoal/FGV/git/TCC")
setwd("./")
```

---
```{r Carrega bibliotecas necessarias, message=FALSE, warning=TRUE, include=FALSE}
if(!require(data.table)) {
  install.packages("data.table")
  library(data.table)
}

if(!require(network)) {
  install.packages("network")
  library(network)
}

if(!require(sna)) {
  install.packages("sna")
  library(sna)
}

if(!require(rgl)) {
  install.packages("rgl")
  library(rgl)
}

```

```{r}
CONSULTAS_CONS <- fread("consultas_cons_cap7.csv", drop = c("V1"))
```

# MapReduce

```{r MapReduce}
CID_Precip_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$Precip, digits = 0)))
names(CID_Precip_freq) <- c("CID","Precip","Freq")

CID_TMax_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$TMax, digits = 0)))
names(CID_TMax_freq) <- c("CID","TMax","Freq")

CID_Tmin_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$TMin, digits = 0)))
names(CID_Tmin_freq) <- c("CID","TMin","Freq")

CID_Ins_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$Ins, digits = 0)))
names(CID_Ins_freq) <- c("CID","Ins","Freq")

CID_EvapPiche_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$EvapPiche, digits = 0)))
names(CID_EvapPiche_freq) <- c("CID","EvapPiche","Freq")

CID_TempCompMed_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$TempCompMedia, digits = 0)))
names(CID_TempCompMed_freq) <- c("CID","TempCompMedia","Freq")

CID_UmidRelMed_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$UmidRelMed, digits = 0)))
names(CID_UmidRelMed_freq) <- c("CID","UmidRelMed","Freq")

CID_VelVentMed_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round(CONSULTAS_CONS$VelVentMed, digits = 0)))
names(CID_VelVentMed_freq) <- c("CID","VelVentMed","Freq")

CID_TDelta_freq <- as.data.frame(table(CONSULTAS_CONS$CID,round((CONSULTAS_CONS$TMax - CONSULTAS_CONS$TMin), digits = 0)))
names(CID_TDelta_freq) <- c("CID","TDelta","Freq")


```


```{r}
CID_EvapPiche_freq$FreqRel <- CID_EvapPiche_freq$Freq/nrow(CONSULTAS_CONS)
CID_Ins_freq$FreqRel <- CID_Ins_freq$Freq/nrow(CONSULTAS_CONS)
CID_Precip_freq$FreqRel <- CID_Precip_freq$Freq/nrow(CONSULTAS_CONS)
CID_TDelta_freq$FreqRel <- CID_TDelta_freq$Freq/nrow(CONSULTAS_CONS)
CID_TempCompMed_freq$FreqRel <- CID_TempCompMed_freq$Freq/nrow(CONSULTAS_CONS)
CID_TMax_freq$FreqRel <- CID_TMax_freq$Freq/nrow(CONSULTAS_CONS)
CID_Tmin_freq$FreqRel <- CID_Tmin_freq$Freq/nrow(CONSULTAS_CONS)
CID_UmidRelMed_freq$FreqRel <- CID_UmidRelMed_freq$Freq/nrow(CONSULTAS_CONS)
CID_VelVentMed_freq$FreqRel <- CID_VelVentMed_freq$Freq/nrow(CONSULTAS_CONS)

```



```{r}

nrow <- max(unique(as.integer(CID_EvapPiche_freq$CID)))
ncol <- max(unique(as.integer(CID_EvapPiche_freq$EvapPiche)))

MATRIX_EVAPPICHE <- matrix(CID_EvapPiche_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_EVAPPICHE) <- unique(CID_EvapPiche_freq$CID)
colnames(MATRIX_EVAPPICHE) <- unique(CID_EvapPiche_freq$EvapPiche)

```

```{r}

nrow <- max(unique(as.integer(CID_Ins_freq$CID)))
ncol <- max(unique(as.integer(CID_Ins_freq$Ins)))

MATRIX_INS <- matrix(CID_Ins_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_INS) <- unique(CID_Ins_freq$CID)
colnames(MATRIX_INS) <- unique(CID_Ins_freq$Ins)

```

```{r}

nrow <- max(unique(as.integer(CID_Precip_freq$CID)))
ncol <- max(unique(as.integer(CID_Precip_freq$Precip)))

MATRIX_PRECIP <- matrix(CID_Precip_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_PRECIP) <- unique(CID_Precip_freq$CID)
colnames(MATRIX_PRECIP) <- unique(CID_Precip_freq$Precip)

```

```{r}

nrow <- max(unique(as.integer(CID_TDelta_freq$CID)))
ncol <- max(unique(as.integer(CID_TDelta_freq$TDelta)))

MATRIX_TDELTA <- matrix(CID_TDelta_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_TDELTA) <- unique(CID_TDelta_freq$CID)
colnames(MATRIX_TDELTA) <- unique(CID_TDelta_freq$TDelta)

```

```{r}

nrow <- max(unique(as.integer(CID_TempCompMed_freq$CID)))
ncol <- max(unique(as.integer(CID_TempCompMed_freq$TempCompMedia)))

MATRIX_TEMPCOMPMED <- matrix(CID_TempCompMed_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_TEMPCOMPMED) <- unique(CID_TempCompMed_freq$CID)
colnames(MATRIX_TEMPCOMPMED) <- unique(CID_TempCompMed_freq$TempCompMedia)

```

```{r}

nrow <- max(unique(as.integer(CID_TMax_freq$CID)))
ncol <- max(unique(as.integer(CID_TMax_freq$TMax)))

MATRIX_TMAX <- matrix(CID_TMax_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMAX) <- unique(CID_TMax_freq$CID)
colnames(MATRIX_TMAX) <- unique(CID_TMax_freq$TMax)


```

```{r}

nrow <- max(unique(as.integer(CID_Tmin_freq$CID)))
ncol <- max(unique(as.integer(CID_Tmin_freq$TMin)))

MATRIX_TMIN <- matrix(CID_Tmin_freq$Freq, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMIN) <- unique(CID_Tmin_freq$CID)
colnames(MATRIX_TMIN) <- unique(CID_Tmin_freq$TMin)


```

```{r}

nrow <- max(unique(as.integer(CID_UmidRelMed_freq$CID)))
ncol <- max(unique(as.integer(CID_UmidRelMed_freq$UmidRelMed)))

MATRIX_UMIDRELMED <- matrix(CID_UmidRelMed_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_UMIDRELMED) <- unique(CID_UmidRelMed_freq$CID)
colnames(MATRIX_UMIDRELMED) <- unique(CID_UmidRelMed_freq$UmidRelMed)

```

```{r}

nrow <- max(unique(as.integer(CID_VelVentMed_freq$CID)))
ncol <- max(unique(as.integer(CID_VelVentMed_freq$VelVentMed)))

MATRIX_VELVENTMED <- matrix(CID_VelVentMed_freq$Freq, nrow = nrow, ncol = ncol)


rownames(MATRIX_VELVENTMED) <- unique(CID_VelVentMed_freq$CID)
colnames(MATRIX_VELVENTMED) <- unique(CID_VelVentMed_freq$VelVentMed)

```



```{r}

nrow <- max(unique(as.integer(CID_EvapPiche_freq$CID)))
ncol <- max(unique(as.integer(CID_EvapPiche_freq$EvapPiche)))

MATRIX_EVAPPICHE_REL <- matrix(CID_EvapPiche_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_EVAPPICHE_REL) <- unique(CID_EvapPiche_freq$CID)
colnames(MATRIX_EVAPPICHE_REL) <- unique(CID_EvapPiche_freq$EvapPiche)

```

```{r}

nrow <- max(unique(as.integer(CID_Ins_freq$CID)))
ncol <- max(unique(as.integer(CID_Ins_freq$Ins)))

MATRIX_INS_REL <- matrix(CID_Ins_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_INS_REL) <- unique(CID_Ins_freq$CID)
colnames(MATRIX_INS_REL) <- unique(CID_Ins_freq$Ins)

```

```{r}

nrow <- max(unique(as.integer(CID_Precip_freq$CID)))
ncol <- max(unique(as.integer(CID_Precip_freq$Precip)))

MATRIX_PRECIP_REL <- matrix(CID_Precip_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_PRECIP_REL) <- unique(CID_Precip_freq$CID)
colnames(MATRIX_PRECIP_REL) <- unique(CID_Precip_freq$Precip)

```

```{r}

nrow <- max(unique(as.integer(CID_TDelta_freq$CID)))
ncol <- max(unique(as.integer(CID_TDelta_freq$TDelta)))

MATRIX_TDELTA_REL <- matrix(CID_TDelta_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_TDELTA_REL) <- unique(CID_TDelta_freq$CID)
colnames(MATRIX_TDELTA_REL) <- unique(CID_TDelta_freq$TDelta)

```

```{r}

nrow <- max(unique(as.integer(CID_TempCompMed_freq$CID)))
ncol <- max(unique(as.integer(CID_TempCompMed_freq$TempCompMedia)))

MATRIX_TEMPCOMPMED_REL <- matrix(CID_TempCompMed_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_TEMPCOMPMED_REL) <- unique(CID_TempCompMed_freq$CID)
colnames(MATRIX_TEMPCOMPMED_REL) <- unique(CID_TempCompMed_freq$TempCompMedia)

```

```{r}

nrow <- max(unique(as.integer(CID_TMax_freq$CID)))
ncol <- max(unique(as.integer(CID_TMax_freq$TMax)))

MATRIX_TMAX_REL <- matrix(CID_TMax_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMAX_REL) <- unique(CID_TMax_freq$CID)
colnames(MATRIX_TMAX_REL) <- unique(CID_TMax_freq$TMax)


```

```{r}

nrow <- max(unique(as.integer(CID_Tmin_freq$CID)))
ncol <- max(unique(as.integer(CID_Tmin_freq$TMin)))

MATRIX_TMIN_REL <- matrix(CID_Tmin_freq$FreqRel, nrow = nrow, ncol = ncol)

rownames(MATRIX_TMIN_REL) <- unique(CID_Tmin_freq$CID)
colnames(MATRIX_TMIN_REL) <- unique(CID_Tmin_freq$TMin)


```

```{r}

nrow <- max(unique(as.integer(CID_UmidRelMed_freq$CID)))
ncol <- max(unique(as.integer(CID_UmidRelMed_freq$UmidRelMed)))

MATRIX_UMIDRELMED_REL <- matrix(CID_UmidRelMed_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_UMIDRELMED_REL) <- unique(CID_UmidRelMed_freq$CID)
colnames(MATRIX_UMIDRELMED_REL) <- unique(CID_UmidRelMed_freq$UmidRelMed)

```

```{r}

nrow <- max(unique(as.integer(CID_VelVentMed_freq$CID)))
ncol <- max(unique(as.integer(CID_VelVentMed_freq$VelVentMed)))

MATRIX_VELVENTMED_REL <- matrix(CID_VelVentMed_freq$FreqRel, nrow = nrow, ncol = ncol)


rownames(MATRIX_VELVENTMED_REL) <- unique(CID_VelVentMed_freq$CID)
colnames(MATRIX_VELVENTMED_REL) <- unique(CID_VelVentMed_freq$VelVentMed)

```



Análises Grafos - Evaporação do Piche - Frequência Nominal

```{r}
dim(MATRIX_EVAPPICHE)
```

```{r}
sna::degree(MATRIX_EVAPPICHE,gmode="digraph",cmode="freeman")
```

```{r}
sna::closeness(MATRIX_EVAPPICHE,gmode="digraph")
```

```{r}
sna::betweenness(MATRIX_EVAPPICHE,gmode="digraph")
```

```{r}
sna::bicomponent.dist(MATRIX_EVAPPICHE)
```

```{r}
sna::bicomponent.dist(MATRIX_EVAPPICHE, symmetrize = c("strong", "weak"))
```

```{r}
sna::components(MATRIX_EVAPPICHE,connected="weak")
```

```{r}
sna::components(MATRIX_EVAPPICHE,connected="strong")
```

```{r}
sna::cug.test(MATRIX_EVAPPICHE,gtrans,cmode="size") 
```

```{r}
sna::cug.test(MATRIX_EVAPPICHE,gtrans,cmode="edges") 
```

```{r}
sna::cug.test(MATRIX_EVAPPICHE,gtrans,cmode="dyad.census")
```

```{r}
sna::diag.remove(MATRIX_EVAPPICHE)
```

```{r}
sna::efficiency(MATRIX_EVAPPICHE)
```

```{r}
sna::gden(MATRIX_EVAPPICHE)
```

```{r}

gplot(MATRIX_EVAPPICHE,gmode="twomode",displaylabels = TRUE,
      edge.col="gray",label.cex = 0.7,usearrows=FALSE,
      vertex.cex = closeness(MATRIX_EVAPPICHE,gmode="twomode")*3)
```

```{r}

eq <- equiv.clust(MATRIX_EVAPPICHE)
plot(eq)
gplot(diag.remove(MATRIX_EVAPPICHE))
```

```{r}

######################### SNA

# Find the Central Graph of a Labeled Graph Stack
cg <- centralgraph(MATRIX_EVAPPICHE)
gplot3d(cg)
```

```{r}

# Compute The Closeness Centrality Scores Of Network Positions
closeness(MATRIX_EVAPPICHE)
```

```{r}

# Find weak components
components(MATRIX_EVAPPICHE,connected="weak")
```

```{r}

# Find strong components
components(MATRIX_EVAPPICHE,connected="strong")
```

```{r}

# Compute Graph Efficiency Scores
efficiency(MATRIX_EVAPPICHE, g=NULL, diag=FALSE)
```

```{r}

# Compute The Degree Centrality Scores Of Network Positions
degree(MATRIX_EVAPPICHE, g=1, nodes=NULL, gmode="digraph", diag=FALSE, tmaxdev=FALSE, cmode="freeman", rescale=FALSE, ignore.eval=FALSE)
```

```{r}

# Find The Density Of A Graph
gden(MATRIX_EVAPPICHE)

```

Análises Grafos - Precipitação - Frequência Nominal

```{r}
dim(MATRIX_PRECIP)
```

```{r}
sna::degree(MATRIX_PRECIP,gmode="digraph",cmode="freeman")
```

```{r}
sna::closeness(MATRIX_PRECIP,gmode="digraph")
```

```{r}
sna::betweenness(MATRIX_PRECIP,gmode="digraph")
```

```{r}
sna::bicomponent.dist(MATRIX_PRECIP)
```

```{r}
sna::bicomponent.dist(MATRIX_PRECIP, symmetrize = c("strong", "weak"))
```

```{r}
sna::components(MATRIX_PRECIP,connected="weak")
```

```{r}
sna::components(MATRIX_PRECIP,connected="strong")
```

```{r}
sna::cug.test(MATRIX_PRECIP,gtrans,cmode="size") 
```

```{r}
sna::cug.test(MATRIX_PRECIP,gtrans,cmode="edges") 
```

```{r}
sna::cug.test(MATRIX_PRECIP,gtrans,cmode="dyad.census")
```

```{r}
sna::diag.remove(MATRIX_PRECIP)
```

```{r}
sna::efficiency(MATRIX_PRECIP)
```

```{r}
sna::gden(MATRIX_PRECIP)
```

```{r}

gplot(MATRIX_PRECIP,gmode="twomode",displaylabels = TRUE,
      edge.col="gray",label.cex = 0.7,usearrows=FALSE,
      vertex.cex = closeness(MATRIX_PRECIP,gmode="twomode")*3)
```

```{r}

eq <- equiv.clust(MATRIX_PRECIP)
plot(eq)
# gplot(diag.remove(MATRIX_PRECIP))
```

```{r}

######################### SNA

# Find the Central Graph of a Labeled Graph Stack
cg <- centralgraph(MATRIX_PRECIP)
gplot3d(cg)
```

```{r}

# Compute The Closeness Centrality Scores Of Network Positions
closeness(MATRIX_PRECIP)
```

```{r}

# Find weak components
components(MATRIX_PRECIP,connected="weak")
```

```{r}

# Find strong components
components(MATRIX_PRECIP,connected="strong")
```

```{r}

# Compute Graph Efficiency Scores
efficiency(MATRIX_PRECIP, g=NULL, diag=FALSE)
```

```{r}

# Compute The Degree Centrality Scores Of Network Positions
degree(MATRIX_PRECIP, g=1, nodes=NULL, gmode="digraph", diag=FALSE, tmaxdev=FALSE, cmode="freeman", rescale=FALSE, ignore.eval=FALSE)
```

```{r}

# Find The Density Of A Graph
gden(MATRIX_PRECIP)

```


Análises Grafos - Variação de Tempertura (Delta) - Frequência Nominal

```{r}
dim(MATRIX_TDELTA)
```

```{r}
sna::degree(MATRIX_TDELTA,gmode="digraph",cmode="freeman")
```

```{r}
sna::closeness(MATRIX_TDELTA,gmode="digraph")
```

```{r}
sna::betweenness(MATRIX_TDELTA,gmode="digraph")
```

```{r}
sna::bicomponent.dist(MATRIX_TDELTA)
```

```{r}
sna::bicomponent.dist(MATRIX_TDELTA, symmetrize = c("strong", "weak"))
```

```{r}
sna::components(MATRIX_TDELTA,connected="weak")
```

```{r}
sna::components(MATRIX_TDELTA,connected="strong")
```

```{r}
sna::cug.test(MATRIX_TDELTA,gtrans,cmode="size") 
```

```{r}
sna::cug.test(MATRIX_TDELTA,gtrans,cmode="edges") 
```

```{r}
sna::cug.test(MATRIX_TDELTA,gtrans,cmode="dyad.census")
```

```{r}
sna::diag.remove(MATRIX_TDELTA)
```

```{r}
sna::efficiency(MATRIX_TDELTA)
```

```{r}
sna::gden(MATRIX_TDELTA)
```

```{r}

gplot(MATRIX_TDELTA,gmode="twomode",displaylabels = TRUE,
      edge.col="gray",label.cex = 0.7,usearrows=FALSE,
      vertex.cex = closeness(MATRIX_TDELTA,gmode="twomode")*3)
```

```{r}

eq <- equiv.clust(MATRIX_TDELTA)
plot(eq)
# gplot(diag.remove(MATRIX_TDELTA))
```

```{r}

######################### SNA

# Find the Central Graph of a Labeled Graph Stack
cg <- centralgraph(MATRIX_TDELTA)
gplot3d(cg)
```

```{r}

# Compute The Closeness Centrality Scores Of Network Positions
closeness(MATRIX_TDELTA)
```

```{r}

# Find weak components
components(MATRIX_TDELTA,connected="weak")
```

```{r}

# Find strong components
components(MATRIX_TDELTA,connected="strong")
```

```{r}

# Compute Graph Efficiency Scores
efficiency(MATRIX_TDELTA, g=NULL, diag=FALSE)
```

```{r}

# Compute The Degree Centrality Scores Of Network Positions
degree(MATRIX_TDELTA, g=1, nodes=NULL, gmode="digraph", diag=FALSE, tmaxdev=FALSE, cmode="freeman", rescale=FALSE, ignore.eval=FALSE)
```

```{r}

# Find The Density Of A Graph
gden(MATRIX_TDELTA)

```


Análises Grafos - Evaporação do Piche - Frequência Relativa

```{r}
dim(MATRIX_EVAPPICHE_REL)
```

```{r}
sna::degree(MATRIX_EVAPPICHE_REL,gmode="digraph",cmode="freeman")
```

```{r}
sna::closeness(MATRIX_EVAPPICHE_REL,gmode="digraph")
```

```{r}
sna::betweenness(MATRIX_EVAPPICHE_REL,gmode="digraph")
```

```{r}
sna::bicomponent.dist(MATRIX_EVAPPICHE_REL)
```

```{r}
sna::bicomponent.dist(MATRIX_EVAPPICHE_REL, symmetrize = c("strong", "weak"))
```

```{r}
sna::components(MATRIX_EVAPPICHE_REL,connected="weak")
```

```{r}
sna::components(MATRIX_EVAPPICHE_REL,connected="strong")
```

```{r}
sna::cug.test(MATRIX_EVAPPICHE_REL,gtrans,cmode="size") 
```

```{r}
sna::cug.test(MATRIX_EVAPPICHE_REL,gtrans,cmode="edges") 
```

```{r}
sna::cug.test(MATRIX_EVAPPICHE_REL,gtrans,cmode="dyad.census")
```

```{r}
sna::diag.remove(MATRIX_EVAPPICHE_REL)
```

```{r}
sna::efficiency(MATRIX_EVAPPICHE_REL)
```

```{r}
sna::gden(MATRIX_EVAPPICHE_REL)
```

```{r}

gplot(MATRIX_EVAPPICHE_REL,gmode="twomode",displaylabels = TRUE,
      edge.col="gray",label.cex = 0.7,usearrows=FALSE,
      vertex.cex = closeness(MATRIX_EVAPPICHE_REL,gmode="twomode")*3)

```

```{r}

eq <- equiv.clust(MATRIX_EVAPPICHE_REL)
plot(eq)
# gplot(diag.remove(MATRIX_EVAPPICHE_REL))

```

```{r}
######################### SNA

# Find the Central Graph of a Labeled Graph Stack
cg <- centralgraph(MATRIX_EVAPPICHE_REL)
gplot3d(cg)

```

```{r}
# Compute The Closeness Centrality Scores Of Network Positions
closeness(MATRIX_EVAPPICHE_REL)

```

```{r}
# Find weak components
components(MATRIX_EVAPPICHE_REL,connected="weak")

```

```{r}
# Find strong components
components(MATRIX_EVAPPICHE_REL,connected="strong")

```

```{r}
# Compute Graph Efficiency Scores
efficiency(MATRIX_EVAPPICHE_REL, g=NULL, diag=FALSE)

```

```{r}
# Compute The Degree Centrality Scores Of Network Positions
degree(MATRIX_EVAPPICHE_REL, g=1, nodes=NULL, gmode="digraph", diag=FALSE, tmaxdev=FALSE, cmode="freeman", rescale=FALSE, ignore.eval=FALSE)

```

```{r}
# Find The Density Of A Graph
gden(MATRIX_EVAPPICHE_REL)

```



