---
title: "Tarefa 2"
author: "Gustavo Hotta (A56865193), Rafael Furlan (A56871487), Ricardo Squassina Lee (A56843646)"
date: "6/18/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, include=FALSE}
#Iniciando o ambiente
rm(list = ls())
cat("\014") 
```

```{r message=FALSE, warning=TRUE, include=FALSE}
#Load required packages
if(!require(devtools)) {
  install.packages("devtools")
  library(devtools)
}

if(!require(ggmap)) {
  #install.packages("ggmap")
  devtools::install_github("dkahle/ggmap")
  library(ggmap)
}

if(!require(readxl)) {
  install.packages("readxl")
  library(readxl)
}

if(!require(googleway)) {
  install.packages("googleway")
  library(googleway)
}

```

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#Teste de Mapas
endereco <- c("Av Paulista 548 Sao Paulo Brazil")
geo_end <- geocode(endereco)
mapa <- get_map(location = geo_end, zoom = 19, maptype = "hybrid", source = "google")
ggmap(mapa) + geom_point(aes(x = geo_end$lon, y = geo_end$lat), color="red", size=3, alpha=0.5)
```

```{r}
EMPRESAS_Paulista_T4 <- read_excel("EMPRESAS_Paulista T4.xlsx")
#View(EMPRESAS_Paulista_T4)

EMPRESAS_GRUPO <- EMPRESAS_Paulista_T4[EMPRESAS_Paulista_T4$`Gestor da Empresa`=="GUSTAVO FUNAYAMA HOTTA" | EMPRESAS_Paulista_T4$`Gestor da Empresa`=="RAFAEL GUSTAVO FURLAN" | EMPRESAS_Paulista_T4$`Gestor da Empresa`=="RICARDO SQUASSINA LEE",]

#geocodeQueryCheck()
register_google(key = readLines(con <- file("api.key")))
EMPRESAS_GRUPO$GEOCODE <- geocode(EMPRESAS_GRUPO$CEP, source = "google", output = "more", override_limit = TRUE)

#EMPRESAS_GRUPO$GEOCODE <- google_geocode(address = "Brazil", components = EMPRESAS_GRUPO$CEP, key = "AIzaSyDtKeCA0LOQ9T__Yj2pKWlr5T54g0bPoNQ")

geocodeQueryCheck()

#i <- 1
#while (i < length(EMPRESAS_GRUPO$ID)) {
#  print(EMPRESAS_GRUPO$CEP[i])
#  EMPRESAS_GRUPO$GEOCODE <- geocode(EMPRESAS_GRUPO$CEP[i], source = "google", output = "more")
#  Sys.sleep(1)
#  i <- i + 1
#}

register_google(key = "")
mapa <- get_map(location = "State of Sao Paulo - Brazil", zoom = 5, source = "google")

#EMPRESAS_geocode <- EMPRESAS_GRUPO$GEOCODE

ggmap(mapa) + geom_point(data = EMPRESAS_GRUPO, aes(x = EMPRESAS_GRUPO$GEOCODE[1], y = EMPRESAS_GRUPO$GEOCODE[2], size = EMPRESAS_GRUPO$`Faturamento 2017`), color="red", alpha=0.5)

write.table(EMPRESAS_GRUPO, file = "EMPRESAS_GRUPO.tsv", sep = "\t", fileEncoding = "UTF-8", row.names = FALSE, col.names = TRUE)

```

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
require(readxl)
EMPRESAS_Paulista_T4 <- read_excel("EMPRESAS_Paulista T4.xlsx")
#View(EMPRESAS_Paulista_T4)

EMPRESAS_GRUPO <- EMPRESAS_Paulista_T4[EMPRESAS_Paulista_T4$`Gestor da Empresa`=="GUSTAVO FUNAYAMA HOTTA" | EMPRESAS_Paulista_T4$`Gestor da Empresa`=="RAFAEL GUSTAVO FURLAN" | EMPRESAS_Paulista_T4$`Gestor da Empresa`=="RICARDO SQUASSINA LEE",]

#install.packages("ggmap")
require(ggmap)
geo_end_empresas <- geocode(EMPRESAS_GRUPO$CEP)

mapa <- get_map(location = "State of Sao Paulo - Brazil", zoom = 5)

ggmap(mapa) + geom_point(data = geo_end_empresas, aes(x = geo_end_empresas$lon, y = geo_end_empresas$lat, size = EMPRESAS_GRUPO$`Faturamento 2017`), color="red", alpha=0.5)
```