Alienation67   ->  Anomia67,      NA,      1
Alienation67   ->  Powerless67,   lam1,   NA
Alienation71   ->  Anomia71,      NA,      1
Alienation71   ->  Powerless71,   lam2,   NA
SES            ->  Education,     NA,      1
SES            ->  SEI,           lam3,   NA
Alienation67   ->  Alienation71,  beta,   NA
SES            ->  Alienation67,  gam1,   NA
SES            ->  Alienation71,  gam2,   NA
SES           <->  SES,           phi,    NA
Alienation67  <->  Alienation67,  psi1,   NA
Alienation71  <->  Alienation71,  psi2,   NA
Anomia67      <->  Anomia67,      the11,  NA
Powerless67   <->  Powerless67,   the22,  NA
Anomia71      <->  Anomia71,      the33,  NA
Powerless71   <->  Powerless71,   the44,  NA
Education     <->  Education,     thd1,   NA
SEI           <->  SEI,           thd2,   NA